name: Continuous Deployment

on:
  workflow_run:
    workflows: ['Continuous Integration']
    branches:
      - 'main'
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4 # Using v4 for stability
        with:
          aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Build and Tag Docker Images
        run: |
          # Build Backend
          docker build -t ridewise/production/backend:latest ./backend/
          docker tag ridewise/production/backend:latest 740186513331.dkr.ecr.us-east-2.amazonaws.com/ridewise/production:backend-latest

          # Build Frontend
          docker build --no-cache -t ridewise/production/frontend:latest ./frontend/
          docker tag ridewise/production/frontend:latest 740186513331.dkr.ecr.us-east-2.amazonaws.com/ridewise/production:frontend-latest

      - name: Push Docker Images to ECR
        run: |
          docker push 740186513331.dkr.ecr.us-east-2.amazonaws.com/ridewise/production:backend-latest
          docker push 740186513331.dkr.ecr.us-east-2.amazonaws.com/ridewise/production:frontend-latest

      - name: Create Deployment Package
        run: |
          zip -r deployment.zip appspec.yml deploy/scripts/install_dependencies.sh deploy/scripts/start_application.sh

      - name: Upload Deployment Package to S3
        run: |
          aws s3 cp deployment.zip s3://ridewisebucket/deployment.zip

      - name: Trigger CodeDeploy Deployment
        run: |
          aws deploy create-deployment \
            --application-name RideWise-CodeDeploy-Application \
            --deployment-group-name RideWise-CodeDeploy-Group \
            --s3-location bucket=ridewisebucket,key=deployment.zip,bundleType=zip \
            --file-exists-behavior OVERWRITE \
            --description "Deployment From Github Actions"
